definitions:
  models.Actor:
    properties:
      avatar_url:
        type: string
      display_login:
        type: string
      gravatar_id:
        type: string
      id:
        type: integer
      login:
        type: string
      url:
        type: string
    type: object
  models.Event:
    properties:
      actor:
        properties:
          avatar_url:
            type: string
          display_login:
            type: string
          gravatar_id:
            type: string
          id:
            type: integer
          login:
            type: string
          url:
            type: string
        type: object
      created_at:
        type: string
      id:
        type: string
      payload:
        additionalProperties: {}
        type: object
      public:
        type: boolean
      repo:
        properties:
          id:
            type: integer
          name:
            type: string
          stars:
            type: integer
          url:
            type: string
        type: object
      type:
        type: string
    type: object
  models.EventRepo:
    properties:
      id:
        type: integer
      name:
        type: string
      stars:
        type: integer
      url:
        type: string
    type: object
  models.Page-models_Event:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/models.Event'
        type: array
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a github events server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Github Events API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /api/v1/events:
    get:
      consumes:
      - '*/*'
      description: List all collected events.
      parameters:
      - description: size of page.
        in: query
        name: size
        required: true
        type: integer
      - description: number of page.
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Page-models_Event'
      summary: List all collected events.
      tags:
      - events
  /api/v1/events/actors:
    get:
      consumes:
      - '*/*'
      description: Gets the actors of recent events.
      parameters:
      - description: amount of recent actors.
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Actor'
            type: array
      summary: Gets the actors of recent events.
      tags:
      - events
  /api/v1/events/count:
    get:
      consumes:
      - '*/*'
      description: Count all collected events.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Count all collected events.
      tags:
      - events
  /api/v1/events/repos:
    get:
      consumes:
      - '*/*'
      description: Gets the repos of recent events.
      parameters:
      - description: amount of recent repos.
        in: query
        name: amount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.EventRepo'
            type: array
      summary: Gets the repos of recent events.
      tags:
      - events
schemes:
- http
swagger: "2.0"
